version: '3.1'

services:
  drupal:
    image: drupal:latest
    ports:
      - "8888:80"
    volumes:
      - drupal-data:/var/www/html/modules/custom
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
      DRUPAL_DB_NAME: drupal
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  drupal-data:
  db-data:
